nested_categoty:
    path:     /nested_categoty
    defaults: { _controller: CategoryPlugin:Default:index }

nested_category_create:
    path:     /nested_categoty/create/{parentId}
    defaults: { _controller: CategoryPlugin:Default:create, parentId:'' }

nested_category_update:
    path:     /nested_categoty/{categoryId}/update
    defaults: { _controller: CategoryPlugin:Default:update}

nested_category_delete:
    path:     /nested_categoty/{categoryId}/delete
    defaults: { _controller: CategoryPlugin:Default:delete}
